#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"


  case "$(uname -s)" in
    Darwin)
      app compile dmg \
        'https://opscode-omnibus-packages.s3.amazonaws.com/mac_os_x/10.11/x86_64/chefdk-0.10.0-1.dmg' \
        'Chef Development Kit' 'chefdk-0.10.0-1.pkg'
      ;;
    Linux)
      curl -sS -L -o chefdk_0.10.0-1_amd64.deb 'https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.10.0-1_amd64.deb'
      sudo dpkg -i ./chefdk_0.10.0-1_amd64.deb
      ;;
  esac
}

bootstrap
}

bootstrap
