#!/usr/bin/env bash

function version {
  local shome="${_chef_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  local ver_chef="$(chef-client --version 2>&- | awk 'NR == 1 {print $2}' || true)"
  jq -n --arg chef "$ver_chef" '{chef: $chef}'
}

version "$@"
